FROM centos/nodejs-6-centos7:latest

EXPOSE 8080

#debug port
EXPOSE 5858

USER root

# Extract app to work dir and copy conf
COPY . ./

RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime && \
    mkdir -p config && \
    chown -R default:root ./

USER default

RUN scl enable rh-nodejs6 "npm install -g forever" && \
    scl enable rh-nodejs6 "npm install --production" && \
    mv conf-docker.json config/conf.json && \
    chmod -R ug+rw ./

RUN echo "node_modules" >> .foreverignore

USER root
RUN  mkdir -p /root/licenses/rhmap/ && \
     cp licenses/* /root/licenses/rhmap/
USER default

ENV FHDEV true

CMD ["forever","-w","--watchDirectory=/opt/app-root/src", "-c", "node --debug", "bin/fhmetsrv.js","config/conf.json","--master-only"]