FROM centos/nodejs-4-centos7

EXPOSE 8080

#debug port
EXPOSE 5858

USER root

# Extract app to work dir and copy conf
COPY . ./

RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime && \
    mkdir -p config && \
    chown -R default:root ./

USER default

RUN scl enable rh-nodejs4 "npm install -g nodemon" && \
    scl enable rh-nodejs4 "npm install --production" && \
    mv conf-docker.json config/conf.json && \
    chmod -R ug+rw ./

ENV FHDEV true

CMD ["bash", "-c", "nodemon --debug=5858 bin/fhmetsrv.js config/conf.json --master-only"]
